# Generated by Django 5.2.3 on 2025-06-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailprovider',
            options={'ordering': ['name'], 'verbose_name': 'Provedor de E-mail', 'verbose_name_plural': 'Provedores de E-mail'},
        ),
        migrations.AlterField(
            model_name='emailprovider',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='emailprovider',
            name='default_sender',
            field=models.EmailField(max_length=254, verbose_name='E-mail do Remetente Padrão'),
        ),
        migrations.AlterField(
            model_name='emailprovider',
            name='host',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Servidor SMTP'),
        ),
        migrations.AlterField(
            model_name='emailprovider',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='emailprovider',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome de exibição'),
        ),
        migrations.AlterField(
            model_name='emailprovider',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Senha SMTP'),
        ),
        migrations.AlterField(
            model_name='emailprovider',
            name='port',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Porta SMTP'),
        ),
        migrations.AlterField(
            model_name='emailprovider',
            name='provider_type',
            field=models.CharField(choices=[('smtp', 'SMTP Manual'), ('mailgun', 'Mailgun'), ('sendgrid', 'SendGrid')], max_length=20, verbose_name='Tipo de Provedor'),
        ),
        migrations.AlterField(
            model_name='emailprovider',
            name='use_ssl',
            field=models.BooleanField(default=False, verbose_name='Usar SSL'),
        ),
        migrations.AlterField(
            model_name='emailprovider',
            name='use_tls',
            field=models.BooleanField(default=True, verbose_name='Usar TLS'),
        ),
        migrations.AlterField(
            model_name='emailprovider',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Usuário SMTP'),
        ),
    ]
